<?php

require_once '../Classes/Databases.php';
require_once '../Classes/SessionsDB.php';

//Load composer's autoloader
require '../Classes/vendor/autoload.php';

$isLoggedIn = new SessionsDB();
    
if(!$isLoggedIn->is_loggedin())
{
	$isLoggedIn->redirect();	
}

date_default_timezone_set("America/Toronto");


$rptfmt = $_POST['rptformat'];

$fromdt = $_POST['fromdt'];
$todt = $_POST['todt'];


		
		$dbobj=Databases::getDB();
        
		$query = 'SELECT rpd.*, 
						 apt.apt_number 
				  FROM rental_payment_details as rpd 
				  INNER JOIN apartments as apt 
						ON apt.apt_id = rpd.apt_id 
				  INNER JOIN users on users.user_id = rpd.user_id
				  WHERE users.user_id = :uid 
						AND
						rpd.payment_date_time >= :fromdt
						AND
						rpd.payment_date_time <= :todt
				  ORDER BY rpd.payment_date_time DESC';
        
		$statement = $dbobj->prepare($query);
        $statement->bindValue(':fromdt', $fromdt." 00:00:00");
        $statement->bindValue(':todt',$todt." 00:00:00");
        $statement->bindValue(':uid',$_SESSION['uid']);
		$statement->execute();
        
		$result = $statement->fetchAll(PDO::FETCH_ASSOC);
        
		$statement->closeCursor();

		
	
	
	
	$tableheader = '<table border="1">
	<tr>
		<td colspan="6"><center>Rent Paid History Report</center></td>
	</tr>
	<tr>
		<td>Starting From :</td>
		<td>'.$fromdt.'
	</tr>
	<tr>
		<td>Ending On :</td>
		<td>'.$todt.'
	</tr>
	<tr>
	<td colspan="6"> </td>
	</tr>
		
					<tr>
						<td>Payment Txn ID</td>
						<td>Payment Date-Time</td>
						<td>Apartment Number</td>
						<td>Month of Payment</td>
						<td>Mode of Payment</td>
						<td>Payment Amount</td>
					<tr>';
					
	if (sizeof($result) > 0) 
	{
		$displaydata = "";
			for($i=0;$i<sizeof($result);$i++) {
			
			$displaydata .= '
				<tr>
					<td>'.$result[$i]['payment_txn_id'].'</td>
					<td>'.$result[$i]['payment_date_time'].'</td>
					<td>'.$result[$i]['apt_number'].'</td>
					<td>'.$result[$i]['payment_month'].'</td>
					<td>'.$result[$i]['payment_mode'].'</td>
					<td>'.$result[$i]['payment_amt'].'</td>
				</tr>';
			}
				
	}
	else {
			$displaydata = "<tr><td colspan='5'><strong><center>No Records found</center></strong></td></tr>";
	}

	$tablefooter = '
			<tr>
				<td colspan="6"> </td>
			</tr>
			<tr>
				<td colspan="6"><center>*** End of Report ***</center></td>
			<tr>
			<tr>
				<td colspan="6"><center>Report Generated by '.$_SESSION['fname'].' on : '.date("Y-m-d H:i:s").'</center></td>
			</tr>
			</table>'; 
		

if($rptfmt == "excel") {


header("Content-Type: application/vnd.ms-excel; charset=utf-8");
header("Content-type: application/x-msexcel; charset=utf-8");
header("Content-Disposition: attachment; filename=RentPaidHist-Report.xls"); 
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Cache-Control: private",false);


		
		
		echo "<html>";

		echo "<body>";
			
			echo $tableheader.$displaydata.$tablefooter;

		echo "</body>";

		echo "</html>";

}
else {
	
		
	$mpdf = new \Mpdf\Mpdf();
	$mpdf->setFooter('Page {PAGENO} of {nb}');
	$mpdf->WriteHTML("<html> <body> ".$tableheader.$displaydata.$tablefooter."</body> </html>");
	$mpdf->Output('RentPaidHist-Report.pdf',\Mpdf\Output\Destination::DOWNLOAD);
	
}

?>
