<?php

require_once '../Classes/Databases.php';
require_once '../Classes/SessionsDB.php';

//Load composer's autoloader
require '../Classes/vendor/autoload.php';

$isLoggedIn = new SessionsDB();
    
if(!$isLoggedIn->is_loggedin())
{
	$isLoggedIn->redirect();	
}

date_default_timezone_set("America/Toronto");


$rptfmt = $_POST['rptformat'];

$fromdt = $_POST['fromdt'];
$todt = $_POST['todt'];

		
		$dbobj=Databases::getDB();
        
		$query = 'SELECT * FROM feedbacks 
							WHERE feedback_date 
							BETWEEN :from_date
								AND 
									:to_date';
        
		$statement = $dbobj->prepare($query);
		$statement->bindValue(':from_date', $fromdt);
        $statement->bindValue(':to_date',$todt);
		$statement->execute();
        
		$result = $statement->fetchAll(PDO::FETCH_ASSOC);
        
		$statement->closeCursor();

		
	
	
	
	$tableheader = '<table border="1">
	<tr>
		<td colspan="7"><center>Feedbacks Report</center></td>
	</tr>
	<tr>
		<td>From Date:</td>
		<td>'.$fromdt.'
	</tr>
	<tr>
		<td>To Date :</td>
		<td>'.$todt.'
	</tr>
	<tr>
	<td colspan="7"> </td>
	</tr>
		
					<tr>
						<td>Feedback ID</td>
						<td>Date of Feedback</td>
						<td>First Name</td>
						<td>Last Name</td>
						<td>Email</td>
						<td>Contact Number</td>
						<td>Feedback Description</td>
						
					<tr>	';
					
	if (sizeof($result) > 0) 
	{
		$displaydata = "";
			for($i=0;$i<sizeof($result);$i++) {
			
			$displaydata = '
				<tr>
					<td>'.$result[$i]['feedback_id'].'</td>
					<td>'.$result[$i]['feedback_date'].'</td>
					<td>'.$result[$i]['first_name'].'</td>
					<td>'.$result[$i]['last_name'].'</td>
					<td>'.$result[$i]['email_id'].'</td>
					<td>'.$result[$i]['contact_num'].'</td>
					<td>'.$result[$i]['feedback_desc'].'</td>
				</tr>';
					
			}
				
	}
	else {
			$displaydata = "<tr><td colspan='7'><strong><center>No Records found</center></strong></td></tr>";
	}

	$tablefooter = '
			<tr>
				<td colspan="7"> </td>
			</tr>
			<tr>
				<td colspan="7"><center>*** End of Report ***</center></td>
			<tr>
			<tr>
				<td colspan="7"><center>Report Generated by '.$_SESSION['fname'].' on : '.date("Y-m-d H:i:s").'</center></td>
			</tr>
			</table>'; 
		

if($rptfmt == "excel") {


header("Content-Type: application/vnd.ms-excel; charset=utf-8");
header("Content-type: application/x-msexcel; charset=utf-8");
header("Content-Disposition: attachment; filename=Feedbacks-Report.xls"); 
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("Cache-Control: private",false);


		
		
		echo "<html>";

		echo "<body>";
			
			echo $tableheader.$displaydata.$tablefooter;

		echo "</body>";

		echo "</html>";

}
else {
	
		
	$mpdf = new \Mpdf\Mpdf();
	
	$mpdf->setFooter('Page {PAGENO} of {nb}');
	$mpdf->WriteHTML("<html> <body> ".$tableheader.$displaydata.$tablefooter."</body> </html>");
	$mpdf->Output('Feedbacks-Report.pdf',\Mpdf\Output\Destination::DOWNLOAD);
	
}

?>
wa